[build]
  base = "/"
  publish = "/"
  command = ""

[context.production]
  publish = "/"
  command = ""

[[redirects]]
  from = "/"
  to = "/automatic_download.html"
  status = 200

  conditions = { referer = [ "https://joaoanes.website" ] }

[[redirects]]
  from = "/embed"
  to = "/JoaoAnesCV.pdf"
  status = 200

[[headers]]
  for = "/JoaoAnesCV.pdf"
  [headers.values]
    Content-Disposition = "attachment; filename=JoaoAnesCV.pdf"
