[build]
  base = "/"
  publish = "/"
  command = ""

[context.production]
  publish = "/"
  command = ""


[[redirects]]
  from = "/embed"
  to = "/JoaoAnesCV.pdf"
  status = 200

[[redirects]]
  from = "/"
  to = "/automatic_download.html"
  status = 200
  force = true
  conditions = { referer = [ "https://joaoanes.website/" ] }

[[headers]]
  for = "/JoaoAnesCV.pdf"
  [headers.values]
    Content-Disposition = "attachment; filename=JoaoAnesCV.pdf"


[[redirects]]
  from = "/"
  to = "/automatic_download.html"
  status = 200
  force = true
  query = {redir = "true"}
